POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 100
}
###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjk5Njc5NDMsInN1YiI6ImNmMmIwNWNhLTU3ZWYtNDY0Zi05MTQxLWJlYjc4NzhjNmZlYyJ9.UTB0dyB7l-ohUll5QaEypjHQlkle9WkdPnl3kF2stJI

###

GET http://localhost:8000/products/9783599d-be92-45b1-890b-bfee28928c45 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/9783599d-be92-45b1-890b-bfee28928c45 HTTP/1.1
Content-Type: application/json

{
  "name": "Product updated",
  "price": 200.00
}

### 
DELETE http://localhost:8000/products/9783599d-be92-45b1-890b-bfee28928c45 HTTP/1.1